---
- name: Include Tasks to load Galaxy credentials to be added to Organizations
  ansible.builtin.include_role:
    name: infra.controller_configuration.filetree_read
    tasks_from: "{{ create_orgs_credentials }}"
  loop:
    - organizations.yml
    - credentials.yml
  loop_control:
    loop_var: create_orgs_credentials

- name: Include Tasks to add Galaxy credentials to Organizations
  ansible.builtin.include_role:
    name: infra.controller_configuration.dispatch
    apply:
      tags:
        - organizations
        - credentials
  vars:
    assign_galaxy_credentials_to_org: false
    controller_configuration_dispatcher_roles:
      - {role: organizations, var: controller_organizations, tags: organizations}
      - {role: credentials, var: controller_credentials, tags: credentials}
...
