---
- name: Set fact to clear token when done
  ansible.builtin.set_fact:
    __clear_token: true
  tags:
    - always

- name: Create a new token using controller username/password
  ansible.controller.token:
    description: 'Creating temporary token for aap-demo-lab'
    scope: "write"
    state: present
    controller_host: "{{ aap_hostname }}"
    controller_username: "{{ aap_username }}"
    controller_password: "{{ aap_password }}"
    validate_certs: "{{ aap_validate_certs }}"
  vars:
    aap_username: "{{ vault_controller_username | default(lookup('env', 'CONTROLLER_USERNAME')) }}"
    aap_password: "{{ vault_controller_password | default(lookup('env', 'CONTROLLER_PASSWORD')) }}"
  register: authtoken_res
  changed_when: false
  tags:
    - always
...
