---
- name: Set some facts for AAP {{ aap_version }}
  ansible.builtin.set_fact:
    controller_hostname: "{{ aap_hostname }}"
    controller_host: "{{ aap_hostname }}"
    controller_validate_certs: "{{ aap_validate_certs }}"
    controller_oauthtoken: "{{ aap_token }}"
  tags:
    - always

- name: FileTree Read for AAP {{ aap_version }}
  ansible.builtin.import_role:
    name: infra.controller_configuration.filetree_read

- name: Dispatch for AAP {{ aap_version }}
  ansible.builtin.import_role:
    name: infra.controller_configuration.dispatch
...
