---
# vars file for org_env_dir_create

org_env_dir_create_paths_common:
  - aap_applications.d
  - aap_organizations.d
  - aap_teams.d
  - aap_user_accounts.d
  - controller_credential_input_sources.d
  - controller_credential_types.d
  - controller_credentials.d
  - controller_execution_environments.d
  - controller_groups.d
  - controller_hosts.d
  - controller_instance_groups.d
  - controller_inventories.d
  - controller_inventory_sources.d
  - controller_job_templates.d
  - controller_labels.d
  - controller_notification_templates.d
  - controller_projects.d
  - controller_roles.d
  - controller_roles.d/team_roles.d
  - controller_roles.d/user_roles.d
  - controller_settings.d
  - controller_schedules.d
  - controller_workflow_job_templates.d
...
