---
controller_templates:
  - name: "Demo - Config as Code - Create Organization"
    description: ""
    organization: "DEMOLab"
    project: "GitHub - lennysh - aap-casc-demo-lab"
    playbook: "demo-casc-create-org.yml"
    inventory: "localhost Inventory"
    execution_environment: "{{ casc_ee_name }}"
    scm_branch: ""
    forks: 0
    limit: ""
    verbosity: 0
    job_type: "run"
    job_slice_count: 1
    use_fact_cache: false
    credentials:
      - "Red Hat Ansible Automation Platform {{ casc_aap_version }}"
      - "Config as Code AAP Version {{ casc_aap_version }}"
    allow_simultaneous: false
    ask_scm_branch_on_launch: false
    ask_diff_mode_on_launch: false
    ask_tags_on_launch: false
    ask_skip_tags_on_launch: false
    ask_job_type_on_launch: false
    ask_verbosity_on_launch: false
    ask_variables_on_launch: false
    ask_inventory_on_launch: false
    ask_limit_on_launch: false
    ask_credential_on_launch: false
    ask_execution_environment_on_launch: false
    ask_labels_on_launch: false
    ask_forks_on_launch: false
    ask_job_slice_count_on_launch: false
    ask_timeout_on_launch: false
    ask_instance_groups_on_launch: false
    job_tags: ""
    force_handlers: false
    skip_tags: ""
    start_at_task: ""
    timeout: 0
    host_config_key: ""
    become_enabled: false
    diff_mode: false
    webhook_service: ""
    prevent_instance_group_fallback: false
    survey_enabled: true
    survey_spec:
      description: ''
      name: ''
      spec:
      - choices: ''
        default: ''
        max: 1024
        min: 1
        new_question: true
        question_description: ''
        question_name: Organization Name to Create
        required: true
        type: text
        variable: gateway_organization_name
      - choices: ''
        default: ''
        max: 1024
        min: 0
        new_question: true
        question_description: ''
        question_name: Organization Description
        required: false
        type: text
        variable: gateway_organization_description
...
