---
aap_applications:
  - name: "DEMOLab Application 02"
    description: ""
    organization: "DEMOLab"
    redirect_uris: "https://demolab.com"
    post_logout_redirect_uris: ""
    algorithm: ""
    user: ""
    client_type: "confidential"
    skip_authorization: "False"
    authorization_grant_type: "authorization-code"
...
